# Generated by Django 5.1.1 on 2024-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_data_source_type_alter_asset_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('MP4', 'Mp4'), ('DOC', 'Doc'), ('TXT', 'Text'), ('JPEG', 'Jpeg'), ('JPG', 'Jpg'), ('PNG', 'Png'), ('MP3', 'Mp3'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='upload_source',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('GOOGLE_DRIVE', 'Google Drive'), ('DROPBOX', 'DropBox'), ('AWS_S3', 'Amazon S3')], default='UPLOAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
