# Generated by Django 5.1.1 on 2024-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_organizationmember_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
