# Generated by Django 5.1.1 on 2024-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organization_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='media_gb_processed_this_month',
            new_name='video_gb_processed_this_month',
        ),
        migrations.AddField(
            model_name='organization',
            name='audio_gb_processed_this_month',
            field=models.FloatField(default=0.0),
        ),
    ]
