# Generated by Django 5.1.1 on 2024-12-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_asset_options_and_more'),
        ('core', '0019_merge_20241217_1222'),
    ]

    operations = [
    ]
