# Generated by Django 5.1.1 on 2025-01-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_task_result_file_url'),
        ('core', '0024_transformation_templates_data'),
    ]

    operations = [
    ]
