# Generated by Django 5.1.1 on 2025-01-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_set_existing_templates_global'),
        ('core', '0032_transformationtemplate_is_global_and_more'),
    ]

    operations = [
    ]
