# Generated by Django 5.1.1 on 2024-10-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='output_column_name',
        ),
        migrations.AddField(
            model_name='action',
            name='output_column_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date')], default='TEXT', max_length=50),
        ),
    ]
