# Generated by Django 5.1.1 on 2024-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_action_output_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='gdrive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('MP4', 'Mp4'), ('DOC', 'Doc'), ('TXT', 'Text'), ('JPEG', 'Jpeg'), ('JPG', 'Jpg'), ('PNG', 'Png'), ('MP3', 'Mp3'), ('OTHER', 'Other')], default='OTHER', max_length=200),
        ),
    ]
