# Generated by Django 5.1.1 on 2024-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_gdrive_credentials_alter_asset_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='s3_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='s3_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
