# Generated by Django 5.1.1 on 2024-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset_s3_bucket_asset_s3_credentials_asset_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dropbox_access_token',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dropbox_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
