# Generated by Django 5.1.1 on 2024-11-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_action_created_by_alter_action_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
