# Generated by Django 5.1.1 on 2024-12-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_metadata_alter_asset_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='upload_source',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('GOOGLE_DRIVE', 'Google Drive'), ('DROPBOX', 'Dropbox'), ('AWS_S3', 'AWS S3')], default='UPLOAD', max_length=20),
        ),
    ]
