# Generated by Django 5.1.1 on 2024-12-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_organizationmember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='current_subscription_plan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stripe_customer_id',
        ),
    ]
