# Generated by Django 5.1.1 on 2024-12-06 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_organization_current_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='media_gb_processed_this_month',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organization',
            name='pdfs_processed_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='usage_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='OrganizationUsage',
        ),
    ]
