# Generated by Django 5.1.1 on 2024-12-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_metadata_alter_asset_file_type_and_more'),
        ('core', '0018_rename_media_gb_processed_this_month_organization_video_gb_processed_this_month_and_more'),
    ]

    operations = [
    ]
